Create request_build_support.yml
serpent-os/recipes pull request #379
Opened 2024-09-13 21:15 UTC by rav101

Template for requesting support for failure to build packages

2024-09-14 10:18 UTC, ermo requested changes
Ikey prefers "Serpent OS" over "SerpentOS" I believe.

2024-09-14 11:05 UTC, rav101 commented
Made the change. I think on the previous templates I've made the same mistake or "SerpentOS" so will review them and make follow on PR's accordingly

2024-09-20 09:33 UTC, ikeycode commented
my man. =) on the other PRs I rectified the branding thing

2024-09-20 09:34 UTC, ikeycode approved these changes

2024-09-20 09:34 UTC, merged